### ISSUE TITLE
Issue with NCT package

### ISSUE THREAD

**Issue by wondang** [cvborkulo/NetworkComparisonTest#22]
Dear all,

I would appreciate your view on Network ComparisonTest using NCT. In particular, I am running the code with my datasets, and the results came out as NA as follow:

nct_results <- NCT(data.hf.p, data.hf.g, it=1000, weighted=TRUE, progressbar = TRUE, test.edges=TRUE, edges='all')

nct_results$glstrinv.sep # connectivity values: NA NA

nct_results$glstrinv.real # difference in connectivity: NA

nct_results$glstrinv.pval # global strength invariance: NA

I am a bit confused about this issue. I am using cross-sectional data, with n1=9000 and n2=5000. The datasets including ordinal, binary, and continuous variables.

Thank you once again for your time and consideration.

**Comment by AndrewLawrence** [comment]
Hi @wondang, the syntax looks OK and that command runs fine using the simulated data from `example('NCT')`.

If the syntax is OK then the problem must be related to your data, or maybe your installation / R environment. If `example("NCT")` runs without error on your R system then it's unlikely to be the installation / environment and probably it's the data.

Can you share your exact dataset(s) here? If not you should try to make a [reproducible example that shows the same error](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using data that you can share (e.g. simulated or permuted).

**Comment by cvborkulo** [comment]
Hi Wondang,

If your data contains multiple types of variables, you need to use mgm for network estimation. If you use the function estimateNetwork() (bootnet package) and specify the right estimation method for each of your dataset, you can feed both results to NCT (as if that is your data). Then it should work for your data.

Best,
Claudia
