### ISSUE TITLE
einv.real and einv.perm are not signed?

### ISSUE THREAD

**Issue by GerardYu** [cvborkulo/NetworkComparisonTest#24]
hi there, 

i ran these few lines:

T1NET.est <- estimateNetwork(data.matrix(T1NET), default = "EBICglasso",corMethod="spearman", weighted = T, signed=T)
T2NET.est <- estimateNetwork(data.matrix(T2NET), default = "EBICglasso",corMethod="spearman", weighted = T, signed=T)

test<-NCT(T1NET.est, T2NET.est, it=500, binary.data=F, weighted=T, paired=T, test.edges=T, test.centrality=T, abs=F, centrality=c("strength", "bridgeStrength"), communities = nodelabels$domain1)

i notice that the test$einv statistics are not signed. On the other hand, the diffcen.real and diffcen.perm are signed. Not sure if its intended to be as such? Is there a reason for this inconsistency?

**Comment by cvborkulo** [comment]
Hi Gerard,

I see now that I did not answer this question. Sorry about that. The latter two are statistics that were added later by another author. Best, Claudia
