### ISSUE TITLE
Network Compariso nTest with dependent samples

### ISSUE THREAD

**Issue by AdvaSegal** [cvborkulo/NetworkComparisonTest#3]
Hi,

I would like to ask few questions about the Network Comparison Test:
1) What are the modifications in the NCT function when analyzing dependent networks (time-series networks)?
2) How to deal with missing data? (it seems that the function works after I remove all the missing data....).
3) What it the best way to examine differences between networks with reference to centrality estimations (strength, betweenness, and closeness)?
 
Thanks for the help.

Adva

**Comment by cvborkulo** [comment]
Dear Adva,

Below, you find a point-by-point answer.

1. When you have two datasets that are dependent, such as pre- post-treatment data in which one group is measured twice, you cannot randomly permute the two datasets. Only the two measurements of the same person can be permuted.
2. NCT cannot handle missing data. You can solve this by only using non-missing data or by imputation. 
3. Currently, NCT only examines strength (node strength) and is validated for this. Other measures can be implemented fairly easy. However, you would have to do a validation study to assess performance of NCT with those measures. 

I hope this helps!
Claudia
