### ISSUE TITLE
Installation problem of the latest version of NetworkComparisonTest

### ISSUE THREAD

**Issue by Karen897-code** [cvborkulo/NetworkComparisonTest#38]
Hi everyone,

If anybody successfully downloaded the latest updated version of the "NetworkComparisonTest" package from Github? It seems like I couldn't download it because of the description file. Do you encounter this problem too? I'm really confused. How can I fix this problem?

Here is my code (which should be right, I've tried "remote" and "devtools" package, and even updated my r version into 4.3.1, but things just still went wrong):
install.packages("remotes")
library(remotes)
remotes::install_github("cvborkulo/NetworkComparisonTest")

Here is the error I recevied:
── R CMD build ──────────────────────────────────────────────────────────────────
✔ checking for file 'C:\Users\hdora\AppData\Local\Temp\RtmpM5Z4oD\remotes84405879a6a\cvborkulo-NetworkComparisonTest-3223c48/DESCRIPTION' ...
─ preparing 'NetworkComparisonTest':
E checking DESCRIPTION meta-information ...
Authors@R field gives more than one person with maintainer role:
Don van den Bergh [cre]
Karoline Huth [cre]
Authors@R field gives no person with maintainer role, valid email
address and non-empty name.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
Error: Failed to install 'NetworkComparisonTest' from GitHub:
! System command 'Rcmd.exe' failed

**Comment by Karen897-code** [comment]
Hi, vandenman!

Thanks for your suggestions agian! I've tried your codes, and it seems like only the second one could work but it reported an error(see below). Does it matter? 

And the present situation is that I've successfully downloaded the new version of the package and I can caculate the bridge expected influence, but the help document of the NCT function is gone, showing me "Internal Server error".

**Code1:**
`remotes::install_github("cvborkulo/NetworkComparisonTest@master")`

**Feedback:**
Downloading GitHub repo cvborkulo/NetworkComparisonTest@master
── R CMD build ──────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\hdora\AppData\Local\Temp\RtmpshevOr\remotes49cc434c1d27\cvborkulo-NetworkComparisonTest-3223c48/DESCRIPTION' ...
─  preparing 'NetworkComparisonTest':
E  checking DESCRIPTION meta-information ... 
   Authors@R field gives more than one person with maintainer role:
     Don van den Bergh [cre]
     Karoline Huth [cre]
   Authors@R field gives no person with maintainer role, valid email
   address and non-empty name.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'NetworkComparisonTest' from GitHub:
  ! System command 'Rcmd.exe' failed

**Code2:**
`remotes::install_github("cvborkulo/NetworkComparisonTest@development")`

**Feedback:**
Downloading GitHub repo cvborkulo/NetworkComparisonTest@development
── R CMD build ──────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\hdora\AppData\Local\Temp\RtmpshevOr\remotes49cc43f322c0\cvborkulo-NetworkComparisonTest-83f650a/DESCRIPTION' ...
─  preparing 'NetworkComparisonTest':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'NetworkComparisonTest_2.2.2.tar.gz'
   
* installing *source* package 'NetworkComparisonTest' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (NetworkComparisonTest)
Error in fetch(key) : 
  lazy-load database 'C:/Users/hdora/AppData/Local/R/win-library/4.3/NetworkComparisonTest/help/NetworkComparisonTest.rdb' is corrupt

**Comment by vandenman** [comment]
Sorry about that, it should be possible to install again with the usual commands. Feel free to reopen if the issue persists.

**Comment by vandenman** [comment]
> Error in fetch(key) :
lazy-load database 'C:/Users/hdora/AppData/Local/R/win-library/4.3/NetworkComparisonTest/help/NetworkComparisonTest.rdb' is corrupt

Means you need to restart R. E.g., in RStudio, click `Session > Restart R`.
